os: linux
dist: bionic
language: c

matrix:
  include:
    # Linux - amd64
    - env: BRANCH=0.20.2
    - env: BRANCH=1.0.10
    - env: BRANCH=1.2.8
    - env: BRANCH=1.4.0
    - env: BRANCH=devel

    # Linux - arm64
    - arch: arm64
      env: BRANCH=1.4.0

    # Linux - ppc64
    - arch: ppc64le
      env: BRANCH=1.4.0

    # macOS - amd64
    - os: osx
      env: BRANCH=0.20.2
    - os: osx
      env: BRANCH=1.0.10
    - os: osx
      env: BRANCH=1.2.8
    - os: osx
      env: BRANCH=1.4.0
    - os: osx
      env: BRANCH=devel

    # windows - amd64
    - os: windows
      env: BRANCH=0.20.2
    - os: windows
      env: BRANCH=1.0.10
    - os: windows
      env: BRANCH=1.2.8
    - os: windows
      env: BRANCH=1.4.0
    - os: windows
      env: BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"
    - "$HOME/Nim"

install:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - bash ./test.sh
